// roadmap — pure renderer: roadmap graph -> SLICES.md string.
// No IO: takes a parsed graph, returns the markdown. render.mjs writes it to a file;
// the MCP mutate tools call it to re-render SLICES.md after editing the YAML, so the
// generated view and the source can never drift.

import {
  flatten, computeWaves, execPlan, sessionsRemaining,
  statusDisplay, emojiFor, isDone, coherenceEnabled,
} from "./graph.mjs";
import { executionDirectiveLines } from "./execution.mjs";
import { tierBadge } from "./priority.mjs";

// renderMarkdown(graph, { cap }) -> string. cap defaults to meta.default_concurrency (or 3).
export function renderMarkdown(graph, opts = {}) {
  const model = flatten(graph);
  const cap = opts.cap != null ? Number(opts.cap) : ((graph.meta && graph.meta.default_concurrency) || 3);
  const links = (graph.meta && graph.meta.links) || {};   // optional repo cross-refs (narrative/status/tracker/bootstrap/strategy)
  const mdlink = (label, path) => (path ? `[\`${path}\`](${path})` : null);

  const B = "`";
  const lines = [];
  const w = (s = "") => lines.push(s);

  // ---- header / intro -------------------------------------------------------
  w("<!-- GENERATED from docs/roadmap/roadmap.yaml by /sync (render.mjs). Do not edit this file directly — edit the YAML and re-render. -->");
  w("# Slices — the pickup-able work catalog");
  w("");
  const introRefs = [
    links.narrative && `mirrored in ${mdlink("narrative", links.narrative)}`,
    (links.status || links.tracker) && `tracked in ${[mdlink("status", links.status), mdlink("tracker", links.tracker)].filter(Boolean).join(" + ")}`,
  ].filter(Boolean);
  w(`> **What this is:** the menu, grouped by PI (Program Increment) with sprints nested under each. Each sprint is a named **slice** you can pick up cold: spin up a session, name the slice, and it reads that slice's prescribed read-order and self-orients. Slice names are the \`/slice\` keys${introRefs.length ? ", " + introRefs.join(", ") : ""}.`);
  w("");
  w("Use `roadmap show <name>` to orient on a menu entry; `roadmap plan` computes ready waves; `roadmap fan` prepares worktrees and can launch an explicitly configured assistant; `roadmap render` refreshes this file after merges. Claude slash skills are optional conveniences where installed.");
  w("");
  // Backlog pointer — emitted only when the repo has a backlog (opts.backlog), so a
  // backlog-free repo renders byte-identically.
  if (opts.backlog) {
    w(`> **Backlog:** ${opts.backlog.open} open item(s) — erratic/follow-up work lives in [\`docs/BACKLOG.md\`](BACKLOG.md); capture with \`/backlog\` or \`roadmap backlog add\`, launch with \`roadmap grab <id>\`.`);
    w("");
  }

  // ---- cross-PI wave map ----------------------------------------------------
  w(`## Ready now — wave map (cap ${cap})`);
  w("");
  w("Derived from the dependency graph: which slices can run concurrently right now, what waits behind them, and what is held on a human. Change the cap with `roadmap plan --cap N` or `roadmap fan --cap N`.");
  w("");
  let waveResult;
  try {
    waveResult = computeWaves(model, cap, { coherence: coherenceEnabled(graph.meta) });
  } catch (e) {
    w(`> ⚠ ${e.message}`);
    waveResult = { waves: [], held: { onHuman: [], blocked: [] } };
  }
  if (waveResult.waves.length === 0) {
    w("_No agent-runnable slices right now._");
  } else {
    waveResult.waves.forEach((wave, i) => {
      w(`**Wave ${i + 1}** — launch concurrently (disjoint files, deps satisfied):`);
      for (const n of wave) {
        const files = [...n.touches, ...n.owns];
        const fileNote = files.length ? ` · touches ${files.map((f) => B + short(f) + B).join(", ")}` : "";
        const badge = tierBadge(n.priority);
        w(`- ${badge ? `**[${badge}]** ` : ""}${B}/slice ${n.invoke}${B} — ${n.what}${fileNote}`);
      }
      w("");
    });
  }
  if (waveResult.held.onHuman.length) {
    w("**Held on a human:**");
    for (const n of waveResult.held.onHuman) {
      w(`- ${B}/slice ${n.invoke}${B} — gated on **${n.gatedOn}** — ${n.what}`);
    }
    w("");
  }
  w("---");
  w("");

  // ---- roadmap: PIs → sprints ----------------------------------------------
  w("## Roadmap — PIs → sprints");
  w("");
  for (const pi of graph.pis) {
    const rem = sessionsRemaining(pi);
    const remStr = rem > 0 ? ` · ~${fmt(rem)} session${rem === 1 ? "" : "s"} remaining` : "";
    const plan = execPlan(pi);
    w(`### ${pi.program_label || pi.id.toUpperCase()} — ${pi.title} · ${statusDisplay(pi.status)}${remStr}`);
    if (pi.theme) w(`> ${pi.theme}`);
    // sprint-status strip
    const strip = (pi.sprints || []).map((s) => `${s.id.toUpperCase()} ${emojiFor(s.status)}`).join(" · ");
    if (strip) w(`> Sprints: ${strip}`);
    // Outcome rollups: group this PI's slices by `outcome` into one founder-review line each
    // (done/total). First-seen order. No slice carries an outcome → no lines (byte-identical).
    const outcomes = new Map();
    for (const s of pi.sprints || []) {
      if (!s.outcome) continue;
      const o = outcomes.get(s.outcome) || { done: 0, total: 0 };
      o.total++; if (isDone(s.status)) o.done++;
      outcomes.set(s.outcome, o);
    }
    for (const [name, o] of outcomes) w(`> OUTCOME ${name}: ${o.done}/${o.total} ${emojiFor("complete")}`);
    if (plan) w(`> Exec plan: ${plan}${pi.exec_hint ? `  _(human hint: ${pi.exec_hint})_` : ""}`);
    if (pi.deps && pi.deps.length) w(`> Deps: ${pi.deps.map((d) => d.toUpperCase()).join(", ")}`);
    if (pi.exit_criteria) w(`> Exit: ${oneLine(pi.exit_criteria)}`);
    w("");
    w("| Sprint | Invoke | Status | Sessions | Deps | What |");
    w("|---|---|---|---|---|---|");
    for (const sp of pi.sprints) {
      const node = model.nodes.find((n) => n.nodeKey === `${pi.id}/${sp.id}`);
      const sess = isDone(sp.status) ? "—" : (typeof sp.est_sessions === "number" ? `~${fmt(sp.est_sessions)}` : "?");
      const deps = depCell(node);
      const prs = (sp.prs && sp.prs.length) ? ` · ${sp.prs.join(" ")}` : "";
      const rcptKeys = sp.receipts ? Object.keys(sp.receipts).filter((k) => sp.receipts[k]) : [];
      const rcpts = rcptKeys.length ? ` · 📎 ${rcptKeys.join(",")}` : "";
      const badge = tierBadge(sp.priority);
      const dtier = sp.dispatch_tier ? ` · ${B}dispatch: ${sp.dispatch_tier}${B}` : "";
      w(`| ${sp.id.toUpperCase()} | ${B}/slice ${sp.invoke}${B} | ${statusDisplay(sp.status, sp.status_label)}${badge ? ` · **${badge}**` : ""}${dtier} | ${sess} | ${deps} | ${sp.what || sp.title}${prs}${rcpts} |`);
    }
    w("");
  }
  w("---");
  w("");

  // ---- recently completed ---------------------------------------------------
  const completed = model.nodes.filter((n) => isDone(n.status) && (n.prs.length || n.completedOn));
  if (completed.length) {
    w(`**Recently completed:**`);
    w("");
    w("| Slice | PI | PRs |");
    w("|---|---|---|");
    for (const n of completed) {
      w(`| ${n.id.toUpperCase()} | ${n.programLabel} | ${n.prs.join(" ") || "—"} |`);
    }
    w("");
  }

  // ---- default gate ---------------------------------------------------------
  if (graph.meta && graph.meta.default_gate) {
    w("**Default verification gate** (every slice, unless its entry overrides `gate`):");
    w("");
    w("```bash");
    w(graph.meta.default_gate.trimEnd());
    w("```");
    w("");
  }
  w("---");
  w("");

  // ---- detail entries (pickup-able = not complete) --------------------------
  w("## Detail — `/slice <name>` reads these");
  w("");
  for (const pi of graph.pis) {
    for (const sp of pi.sprints) {
      if (isDone(sp.status)) continue;
      const node = model.nodes.find((n) => n.nodeKey === `${pi.id}/${sp.id}`);
      w(`### ${B}${sp.invoke}${B}`);
      // Execution directive at the TOP of the read-out (only when the slice declares one — a
      // slice without an execution block renders byte-identically to before).
      const exec = executionDirectiveLines(node);
      if (exec) {
        exec.forEach((line) => w(`> ${line}`));
        w("");
      }
      w(`- **What:** ${sp.what || sp.title}`);
      w(`- **Status:** ${statusDisplay(sp.status, sp.status_label)} (${pi.program_label || pi.id.toUpperCase()}${pi.id ? ` · ${sp.id.toUpperCase()}` : ""})`);
      if (sp.priority && (tierBadge(sp.priority) || sp.priority.weight != null || sp.priority.reason)) {
        const parts = [tierBadge(sp.priority), sp.priority.weight != null ? `weight ${sp.priority.weight}` : null].filter(Boolean).join(" · ");
        w(`- **Priority:** ${parts || "(set)"}${sp.priority.reason ? ` — ${oneLine(sp.priority.reason)}` : ""}`);
      }
      if (node && (node.deps.length || node.piDeps.length)) {
        w(`- **Deps:** ${depCell(node)}`);
      }
      if (sp.read_order && sp.read_order.length) {
        w(`- **Read-order:**`);
        sp.read_order.forEach((r, i) => w(`  ${i + 1}. ${r}`));
      }
      if (sp.resume_action) w(`- **Resume / next action:** ${oneLine(sp.resume_action)}`);
      const gateText = !sp.gate || sp.gate === "default"
        ? "default verification gate"
        : oneLine(sp.gate).replace(/\{\{\s*default\s*\}\}/gi, "default gate");
      w(`- **Gate:** ${gateText}`);
      if (sp.gated_on) w(`- **Gated on:** ${sp.gated_on} (an agent prepares; it does not perform the gate).`);
      w("");
    }
  }

  // ---- footer ---------------------------------------------------------------
  w("---");
  w("");
  w("## Maintaining this catalog");
  w("");
  w("This file is **generated** from [`roadmap/roadmap.yaml`](roadmap/roadmap.yaml). To change it, edit the YAML and run `/sync` (which reconciles statuses against merged PRs + the tracker, then re-renders). `/slice` reads the YAML directly to orient; `/fanout` reads it to compute waves and launch sessions. Slice **invoke keys are stable** — they are the `/slice` keys and are referenced from `ROADMAP.md`.");
  w("");
  const seeAlso = [
    links.narrative && `- **Narrative shape** → ${mdlink("narrative", links.narrative)}`,
    links.bootstrap && `- **Cold-start orientation** → ${mdlink("bootstrap", links.bootstrap)}`,
    (links.status || links.tracker) && `- **Live status** → ${[mdlink("status", links.status), mdlink("tracker", links.tracker)].filter(Boolean).join(" + ")}`,
    links.strategy && `- **Strategy / positioning** → ${mdlink("strategy", links.strategy)}`,
    "- **Resume a specific session** → `/pickup`",
  ].filter(Boolean);
  if (seeAlso.length) {
    w("## See also");
    w("");
    seeAlso.forEach((l) => w(l));
    w("");
  }

  return lines.join("\n") + "\n";

  // ---- helpers --------------------------------------------------------------
  function depCell(node) {
    if (!node) return "—";
    const parts = [];
    for (const d of node.deps) parts.push(d.split("/")[1].toUpperCase());
    for (const p of node.piDeps) parts.push(p.toUpperCase());
    return parts.length ? parts.join(", ") : "—";
  }
  function oneLine(s) {
    return String(s).replace(/\s*\n\s*/g, " ").trim();
  }
  function fmt(n) {
    return String(n);
  }
  function short(p) {
    const segs = String(p).split("/");
    return segs[segs.length - 1] || p;
  }
}
